const Hobbies = [
  'Family',
  'Bridge',
  'Card games',
  'Crossword puzzles',
  'Socializing',
  'Reading',
  'Music',
  'Watching television',
  'Word search',
  'Drawing',
  'Gardening',
  'Singing',
  'Swimming',
  'Sudoku',
  'Crocheting',
  'Cross-stitch',
  'Sewing',
  'News',
  'Woodworking',
  'Poetry',
  'Walking',
  'Bowling',
  'Knitting',
  'Wii',
  'Games',
  'Cribbage',
  'Jigsaw Puzzles',
  'Exercise',
  'Happy Hour',
  'Painting',
  'Dance',
  'Plants',
  'Card collecting',
  'Baking',
  'Word games',
  'Birdwatching',
  'Bingo',
  'Coffee',
  'Travel',
  'Baseball',
  'Curling',
  'Football',
  'Puzzles',
  'Fishing',
  'Golfing',
  'Genealogy',
  'Cooking',
  'Computers',
  'Theatre',
  'Watching movies',
  'Colouring',
  'Photography',
  'Finance',
  'Solitaire',
  'Politics',
  'Research projects',
  'Yoga',
  'Shuffleboard',
  'Quilting',
  'Sports',
  'Shopping',
  'Pottery',
  'Piano',
  'Keyboard instruments',
  'Skating',
  'Crafts',
  'Watching sports',
  'Collecting',
  'Outings',
  'Aqua Fit',
  'Billiards',
  'Running',
  'Camping',
  'Hunting',
  'Bible Study',
  'Computer games',
  'Basketball',
  'Hockey',
  'Scrapbooking',
  'Poker',
  'Art therapy',
  'Mobile games',
  'Writing',
  'Embroidery',
  'Animal watching',
  'Mini Golf',
  'Pets',
  'Rummy',
  'Board games',
  'Calligraphy',
  'Accordion',
  'Mobile devices',
  'Violin',
  'Gambling',
  'Church',
  'Tennis',
  'Tea',
  'Musicals',
  'Entertaining',
] as const

export default Hobbies
